name: Deploy Test Website

on:
  push:
    branches:
      - feat/staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/huydo1.pem ubuntu@ec2-3-85-208-85.compute-1.amazonaws.com 'cd /var/www/staging-frontend && git pull origin feat/staging'
